#ifndef SHADES_VERSION_H
#define SHADES_VERSION_H

#define SHADES_VERSION_MAJOR 2
#define SHADES_VERSION_MINOR 0
#define SHADES_VERSION_PATCH 0
#define SHADES_VERSION_STRING "2.0.0-alpha"
#define SHADES_VERSION_FULL "SHADES v2.0.0-alpha"
#define SHADES_COPYRIGHT "Copyright (c) 2024-2026 azm0de"

#endif // SHADES_VERSION_H
